FROM ividalm/docker-visual-nn:basic-py3

# OpenCV

ENV SRC /usr/local/src
ARG SRC=/usr/local/src

RUN mkdir -p $SRC && \
    cd $SRC && \
    git clone --branch 3.3.0 --depth 1 https://github.com/Itseez/opencv.git && \
    git clone --branch 3.3.0 --depth 1 https://github.com/Itseez/opencv_contrib.git && \
    mkdir -p $SRC/opencv/build && \
    cd $SRC/opencv/build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D INSTALL_C_EXAMPLES=OFF \
          -D INSTALL_PYTHON_EXAMPLES=ON \
          -D OPENCV_EXTRA_MODULES_PATH=$SRC/opencv_contrib/modules \
          -D BUILD_EXAMPLES=ON \
          -D CUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs/libcuda.so \
          -D PYTHON_EXECUTABLE=$(which python3) \
		  -D PYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
		  -D PYTHON_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") .. \
          .. && \
    make -k -j8 && \
    make install &&\
    rm -rf $SRC/opencv && \
    rm -rf $SRC/opencv_contrib && \
    ln /dev/null /dev/raw1394

WORKDIR $SRC
