FROM gcr.io/tensorflow/tensorflow:latest-devel-gpu-py3

#basic installs
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
            git \
            unzip \
            vim \
            wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# installs for OpenCV
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
            pkg-config \
            build-essential \
            cmake \
            libgtk2.0-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libtbb2 \
            libtbb-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libjasper-dev \
            libdc1394-22-dev \
            python3-dev \
            python3-setuptools \
            libboost-all-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# python environment (since it's a docker container, we don't need virtual envs)
RUN pip3 install pytest \
                 tensorboard \
                 h5py \
                 scikit-learn

